[package]
name = "meeseeks_html5ever_nif"
version = "0.4.5"
authors = ["Meeseeks <mmischov@gmail.com>"]

[lib]
name = "meeseeks_html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.14"

html5ever = "0.15.0"
html5ever-atoms = "0.3.0"
tendril = "0.2.3"
lazy_static = "*"
scoped-pool = "1.0.0"
