[package]
name = "meeseeks_html5ever_nif"
version = "0.4.1"
authors = ["Meeseeks <mmischov@gmail.com>"]

[lib]
name = "meeseeks_html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.14"

html5ever = "*"
html5ever-atoms = "*"
tendril = "*"
lazy_static = "*"
scoped-pool = "*"
