[package]
name = "meeseeks_html5ever_nif"
version = "0.6.0"
authors = ["Meeseeks <mmischov@gmail.com>"]

[lib]
name = "meeseeks_html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.14"

html5ever = "0.16.0"
xml5ever = "0.6.0"
markup5ever = "0.1"
tendril = "0.2.3"
lazy_static = "0.2"
scoped-pool = "1.0.0"
